---
- name: restart_ssh
  service:
    name: sshd
    state: restarted
  async: 120       # Allow up to 120 seconds for restart (2 minutes)
  poll: 0          # Don't wait for completion (fire-and-forget)
  ignore_errors: yes  # Continue playbook even if restart fails
  # Note: This asynchronous approach prevents playbook hangs
  # but may require separate verification for critical systems
